version: "3"

services:

  loki:
    container_name: loki
    image: grafana/loki

  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "2020:2020"
      - "24224:24224"
    depends_on:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
      
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "docker_container_nginx_{{ .Name }}_{{ .ID }}"
    depends_on:
      - fluentbit

volumes:
  grafana-storage:
